import React from 'react'
import ServiceHero from '../components/serviceHero/serviceHero'

export default function Page() {
  return (
    <>
        <ServiceHero title=' Политика конфиденциальности' routes={[{title:'Главная', href: '/'}, {title:' Политика конфиденциальности', href: 'policy'}]} className='relative after:absolute after:block bg-[#C4C4C4] after:top-0 after:left-0 after:w-full after:h-full after:z-100 after:bg-[linear-gradient(90deg,rgba(171,53,52,0.5)0%,rgba(255,7,5,0.5)200%)] after:bg-opacity-50'/>
        <section>
            <div className='max-w-c-full mt-[60px] lg:mt-0 mb-6 mx-auto p-6 lg:px-8 font-title text-black font-semibold text-lg md:text-base md:font-medium'>
                Lorem ipsum dolor sit amet consectetur. Auctor fusce sed eleifend viverra nunc mauris elit mi. Id commodo duis nulla eget et fusce amet eu metus. Eget interdum amet pellentesque imperdiet interdum. Eget neque facilisis scelerisque purus. Nibh tincidunt id vitae tellus est. Lorem adipiscing ullamcorper dictum consectetur bibendum morbi mauris lobortis viverra. In eu venenatis odio aliquam euismod purus purus. Euismod ipsum congue erat at pellentesque enim malesuada tempor nulla. Sit volutpat eget ornare diam nullam leo diam ac quis. Morbi elit odio vel sollicitudin tortor euismod scelerisque. Vulputate nullam dui tortor nibh sit. Pharetra est arcu tellus amet risus risus. Ipsum eget adipiscing dignissim faucibus mollis. Odio odio eros vulputate mattis. Nullam interdum dictum integer tempor viverra volutpat id sapien id. Malesuada aliquam curabitur lacinia dui non sapien feugiat. Odio mauris tincidunt sed vitae ut volutpat facilisis. Leo nec pharetra amet sagittis. Aliquet iaculis amet rhoncus ipsum. Pharetra id massa diam feugiat felis natoque consequat venenatis amet. Sed vestibulum non in adipiscing maecenas neque lacus pellentesque. Ullamcorper nam orci ut viverra. Non tellus penatibus arcu et turpis feugiat at. Tellus nulla imperdiet gravida massa. Vitae convallis tempor amet gravida nunc. Id tempor rutrum et at magna. Morbi tempor scelerisque fermentum nunc tellus. Praesent congue euismod blandit sed. Nulla eu bibendum sit arcu et quis. Leo diam lorem donec sit. Ut elementum euismod tempor scelerisque dictum. Leo sit habitant massa non venenatis consequat interdum ut quam. Adipiscing imperdiet morbi nunc quisque viverra elit. Et odio mollis ac odio turpis praesent id aenean eget. Diam vehicula egestas interdum mattis. Sociis sagittis tellus massa ipsum sed consequat maecenas. Vulputate mi aliquam vulputate amet ornare eget elit. Lorem ut sem non accumsan vitae lorem fermentum volutpat. Sed arcu congue rhoncus eget potenti molestie risus nullam pharetra. Quis egestas a at habitasse. Varius a mi nunc nulla viverra ac. Tempus vestibulum mus posuere turpis. Arcu sem lectus eu laoreet. Molestie faucibus ut quis quam sed et nulla. Est aliquet elit enim vestibulum eros sit vel lectus. Ut commodo nulla scelerisque non egestas scelerisque magnis. Ipsum mi ut habitant viverra eu. Volutpat tortor scelerisque nec facilisis. Mauris luctus adipiscing feugiat urna ut vehicula lacus aliquam tempus. Semper pharetra tellus semper non blandit et pellentesque nunc rhoncus. Commodo semper pretium molestie amet lacus libero faucibus sodales. Aliquet nisl vitae urna amet nibh pharetra ultricies nunc eu. Massa aliquam egestas mauris aliquam ut mattis. Praesent neque tempus nunc nisl sed.

                Lorem ipsum dolor sit amet consectetur. Auctor fusce sed eleifend viverra nunc mauris elit mi. Id commodo duis nulla eget et fusce amet eu metus. Eget interdum amet pellentesque imperdiet interdum. Eget neque facilisis scelerisque purus. Nibh tincidunt id vitae tellus est. Lorem adipiscing ullamcorper dictum consectetur bibendum morbi mauris lobortis viverra. In eu venenatis odio aliquam euismod purus purus. Euismod ipsum congue erat at pellentesque enim malesuada tempor nulla. Sit volutpat eget ornare diam nullam leo diam ac quis. Morbi elit odio vel sollicitudin tortor euismod scelerisque. Vulputate nullam dui tortor nibh sit. Pharetra est arcu tellus amet risus risus. Ipsum eget adipiscing dignissim faucibus mollis. Odio odio eros vulputate mattis. Nullam interdum dictum integer tempor viverra volutpat id sapien id. Malesuada aliquam curabitur lacinia dui non sapien feugiat. Odio mauris tincid

                unt sed vitae ut volutpat facilisis. Leo nec pharetra amet sagittis. Aliquet iaculis amet rhoncus ipsum. Pharetra id massa diam feugiat felis natoque consequat venenatis amet. Sed vestibulum non in adipiscing maecenas neque lacus pellentesque. Ullamcorper nam orci ut viverra. Non tellus penatibus arcu et turpis feugiat at. Tellus nulla imperdiet gravida massa. Vitae convallis tempor amet gravida nunc. Id tempor rutrum et at magna. Morbi tempor scelerisque fermentum nunc tellus. Praesent congue euismod blandit sed. Nulla eu bibendum sit arcu et quis. Leo diam lorem donec sit. Ut elementum euismod tempor scelerisque dictum. Leo sit habitant massa non venenatis consequat interdum ut quam. Adipiscing imperdiet morbi nunc quisque viverra elit. Et odio mollis ac odio turpis praesent id aenean eget. Diam vehicula egestas interdum mattis. Sociis sagittis tellus massa ipsum sed consequat maecenas. Vulputate mi aliquam vulputate amet ornare eget elit. Lorem ut sem non accumsan vitae lorem fermentum volutpat. Sed arcu congue rhoncus eget potenti molestie risus nullam pharetra. Quis egestas a at habitasse. Varius a mi nunc nulla viverra ac. Tempus vestibulum mus posuere turpis. Arcu sem lectus eu laoreet. Molestie faucibus ut quis quam sed et nulla. Est aliquet elit enim vestibulum eros sit vel lectus. Ut commodo nulla scelerisque non egestas scelerisque magnis. Ipsum mi ut habitant viverra eu. Volutpat tortor scelerisque nec facilisis. Mauris luctus adipiscing feugiat urna ut vehicula lacus aliquam tempus. Semper pharetra tellus semper non blandit et pellentesque nunc rhoncus. Commodo semper pretium molestie amet lacus libero faucibus sodales. Aliquet nisl vitae urna amet nibh pharetra ultricies nunc eu. Massa aliquam egestas mauris aliquam ut mattis. Praesent neque tempus nunc nisl sed.
            </div>
        </section>
    </>
  )
}
